SELECT
    MAX(fecha) AS fecha_documento,
    dia_semana,
    semana,
    dia_equivalente,
    mes,
    categoria,
    subcategoria,
    linea_2,
    linea_2_2,
    sublinea,
    descripcion_padre,
    coleccion,
    marca,
    v_marca_2              AS marca_2,
    v_marca_temporada      AS marca_temporada,
    v_tipo                  AS tipo,
    v_origen                AS origen,
    v_localidad             AS localidad,
    temporada,
    v_temporada_2           AS temporada_2,
    v_temporada_3           AS temporada_3,
    v_temporada_4           AS temporada_4,
    canal                   AS grupo_canal,
    corner                  AS sucursal,
    v_sucursal_2_1          AS sucursal_2_1,
    v_sucursal_3_1          AS sucursal_3_1,
    v_codigo_padre          AS codigo_padre,
    v_condicion             AS condicion,
    v_mall                  AS mall,
    v_mes_coleccion         AS "_mes_coleccion",
    v_tdas_liquidadoras     AS tdas_liquidadoras,
    filtro_sss2,
    v_filtro_sss            AS filtro_sss,
    MAX(CASE WHEN tipo_fila = 'ventas_act' THEN vta_act  ELSE NULL END) AS importe_subtotal,
    MAX(CASE WHEN tipo_fila = 'ventas_hst' THEN vta_hst  ELSE NULL END) AS importe_subtotal_hst_1,
    MAX(CASE WHEN tipo_fila = 'ventas_act' THEN vta_unds_act ELSE NULL END) AS unidades,
    MAX(CASE WHEN tipo_fila = 'ventas_hst' THEN vta_unds_hst ELSE NULL END) AS unidades_hst_1,
    MAX(CASE WHEN tipo_fila = 'ventas_act' THEN costo_act   ELSE NULL END) AS costo_venta_neta,
    MAX(CASE WHEN tipo_fila = 'ventas_hst' THEN costo_hst   ELSE NULL END) AS costo_venta_neta_hst_1,
    MAX(CASE WHEN tipo_fila = 'metas_std'  THEN meta        ELSE NULL END) AS meta_venta,
    MAX(CASE WHEN tipo_fila = 'metas_std'  THEN meta_contribucion ELSE NULL END) AS meta_contribucion,
    MAX(vta_retail_act)     AS vta_retail_act,
    MAX(vta_retail_hst)     AS vta_retail_hst,
    MAX(nro_tickets)        AS nro_tickets,
    MAX(CASE WHEN tipo_fila = 'ventas_hst' THEN v_nro_tickets_hst_1 ELSE NULL END) AS nro_tickets_hst_1,
    MAX(CASE WHEN tipo_fila = 'ventas_act' THEN v_flag_tickets_act ELSE NULL END) AS flag_tickets_act,
    MAX(CASE WHEN tipo_fila = 'ventas_act' THEN v_flag_tickets_hst ELSE NULL END) AS flag_tickets_hst,
    MAX(CASE WHEN tipo_fila = 'stock_act'  THEN inv_unds_act  ELSE NULL END) AS inv_unds_act,
    MAX(CASE WHEN tipo_fila = 'stock_act'  THEN inv_unds_hst  ELSE NULL END) AS inv_unds_hst,
    MAX(CASE WHEN tipo_fila = 'stock_act'  THEN inv_costo_act ELSE NULL END) AS inv_costo_act,
    MAX(CASE WHEN tipo_fila = 'stock_act'  THEN inv_costo_hst ELSE NULL END) AS inv_costo_hst,
    MAX(cubicaje)           AS cubicaje,
    MAX(area)               AS area,
    MAX(v_dias_estancia)    AS dias_estancia,
    MAX(v_dias_estancia_tda) AS dias_estancia_tda,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN vta_act  ELSE NULL END) AS importe_subtotal_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN vta_hst  ELSE NULL END) AS importe_subtotal_hst_1_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN vta_unds_act ELSE NULL END) AS unidades_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN vta_unds_hst ELSE NULL END) AS unidades_hst_1_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN costo_act   ELSE NULL END) AS costo_venta_neta_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN costo_hst   ELSE NULL END) AS costo_venta_neta_hst_1_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'META'  THEN meta        ELSE NULL END) AS meta_venta_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'META'  THEN meta_contribucion ELSE NULL END) AS meta_contribucion_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN vta_retail_act ELSE NULL END) AS vta_retail_act_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN vta_retail_hst ELSE NULL END) AS vta_retail_hst_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN inv_unds_act  ELSE NULL END) AS inv_unds_act_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN inv_unds_hst  ELSE NULL END) AS inv_unds_hst_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN inv_costo_act ELSE NULL END) AS inv_costo_act_txd,
    MAX(CASE WHEN origen = 'TXD' AND tipo_fila = 'VENTA' THEN inv_costo_hst ELSE NULL END) AS inv_costo_hst_txd
FROM "smartanalytic"."public"."automatizacion_pla_reporte_consolidado"
WHERE (fecha BETWEEN '2025-08-01' AND '2025-08-31')
   OR (fecha BETWEEN '2026-08-01' AND '2026-08-31')
GROUP BY dia_semana, semana, dia_equivalente, mes, categoria, subcategoria, linea_2, linea_2_2, sublinea, descripcion_padre, coleccion, marca, v_marca_2, v_marca_temporada, v_tipo, v_origen, v_localidad, temporada, v_temporada_2, v_temporada_3, v_temporada_4, canal, corner, v_sucursal_2_1, v_sucursal_3_1, v_codigo_padre, v_condicion, v_mall, v_mes_coleccion, v_tdas_liquidadoras, filtro_sss2, v_filtro_sss
ORDER BY fecha_documento, sucursal, marca, categoria;