-- ================================================================
-- AQP01 — Datos de prueba para escenarios de Facturación Electrónica
-- Servidor : 10.20.0.15
-- Base     : SOLUFLEX_FARO
-- Ejecutar : SSMS o sqlcmd conectado directamente a 10.20.0.15
-- ================================================================
USE SOLUFLEX_FARO;
GO

-- ================================================================
-- ESCENARIO 1: FAC nueva (motor la captura automáticamente)
-- Serie esperada: F142-00000693  |  SUNAT tipo 01
-- ================================================================
SET IDENTITY_INSERT [dbo].[CABECERA_DOCUMENTO] ON;

INSERT INTO [dbo].[CABECERA_DOCUMENTO] (
    IDTRANSACCION, CODIGO_DOCUMENTO, NUMERO_SERIE, NUMERO_DOCUMENTO,
    FECHA_DOCUMENTO, CODIGO_MONEDA, TIPO_AUXILIAR,
    IDENTIDAD, NOMBRE, DIRECCION,
    IMPORTE_SUBTOTAL, IMPORTE_IGV, IMPORTE_TOTAL,
    PORC_IMPUESTO, IMPORTE_INAFECTO,
    CODIGO_ESTADO, TIPO_CAMBIO, IDEMPRESA, IDSUCURSAL,
    USUARIO_CREACION, FECHA_CREACION
) VALUES (
    262942, '067', 142, 693,
    GETDATE(), '01', '06',
    '20100070970', 'SUNAT - SUPERINTENDENCIA NACIONAL DE ADUANAS',
    'AV GARCILAZO DE LA VEGA 1472 LIMA',
    423.73, 76.27, 500.00,
    18.00, 0.00,
    '12', 3.368, 1, 172,
    'TEST', GETDATE()
);

SET IDENTITY_INSERT [dbo].[CABECERA_DOCUMENTO] OFF;

SET IDENTITY_INSERT [dbo].[DETALLE_DOCUMENTO] ON;

INSERT INTO [dbo].[DETALLE_DOCUMENTO] (
    IDTRANSACCION, SECUENCIA, CODIGO_PRODUCTO, CANTIDAD,
    PRECIO_UNITARIO, IMPORTE_SUBTOTAL, IMPORTE_IMPUESTO, IMPORTE_TOTAL,
    PORC_IMPUESTO, CODIGO_UNIMED, FLAG_INAFECTO, IMPORTE_ICBPER
) VALUES
    (262942, 1, 'V26MCFL001NEGME', 1.00, 338.9831, 338.98, 61.02, 400.00, 18.00, 'UN', 'N', 0.00),
    (262942, 2, 'P26MCVS002BLAME', 1.00,  84.7458,  84.75, 15.25, 100.00, 18.00, 'UN', 'N', 0.00);

SET IDENTITY_INSERT [dbo].[DETALLE_DOCUMENTO] OFF;
GO

-- ================================================================
-- ESCENARIO 2: NC referenciando la FAC anterior
-- Serie esperada: FC142-00000001  |  SUNAT tipo 07
-- Motivo 07 = Devolución por ítem
-- ================================================================
SET IDENTITY_INSERT [dbo].[CABECERA_DOCUMENTO] ON;

INSERT INTO [dbo].[CABECERA_DOCUMENTO] (
    IDTRANSACCION, CODIGO_DOCUMENTO, NUMERO_SERIE, NUMERO_DOCUMENTO,
    FECHA_DOCUMENTO, CODIGO_MONEDA, TIPO_AUXILIAR,
    IDENTIDAD, NOMBRE, DIRECCION,
    IMPORTE_SUBTOTAL, IMPORTE_IGV, IMPORTE_TOTAL,
    PORC_IMPUESTO, IMPORTE_INAFECTO,
    CODIGO_ESTADO, TIPO_CAMBIO, IDEMPRESA, IDSUCURSAL,
    IDTRANSACCION_ORIGEN, CODIGO_MOTIVO_SUNAT, MOTIVO_SUNAT,
    USUARIO_CREACION, FECHA_CREACION
) VALUES (
    262943, '069', 142, 1,
    GETDATE(), '01', '06',
    '20100070970', 'SUNAT - SUPERINTENDENCIA NACIONAL DE ADUANAS',
    'AV GARCILAZO DE LA VEGA 1472 LIMA',
    84.75, 15.25, 100.00,
    18.00, 0.00,
    '12', 3.368, 1, 172,
    262942, '07', 'DEVOLUCION POR ITEM - PRENDA CON DEFECTO',
    'TEST', GETDATE()
);

SET IDENTITY_INSERT [dbo].[CABECERA_DOCUMENTO] OFF;

SET IDENTITY_INSERT [dbo].[DETALLE_DOCUMENTO] ON;

INSERT INTO [dbo].[DETALLE_DOCUMENTO] (
    IDTRANSACCION, SECUENCIA, CODIGO_PRODUCTO, CANTIDAD,
    PRECIO_UNITARIO, IMPORTE_SUBTOTAL, IMPORTE_IMPUESTO, IMPORTE_TOTAL,
    PORC_IMPUESTO, CODIGO_UNIMED, FLAG_INAFECTO, IMPORTE_ICBPER
) VALUES
    (262943, 1, 'P26MCVS002BLAME', 1.00, 84.7458, 84.75, 15.25, 100.00, 18.00, 'UN', 'N', 0.00);

SET IDENTITY_INSERT [dbo].[DETALLE_DOCUMENTO] OFF;
GO

-- ================================================================
-- ESCENARIO 3: BOL nueva (motor la captura automáticamente)
-- Serie esperada: B142-00048490  |  SUNAT tipo 03
-- ================================================================
SET IDENTITY_INSERT [dbo].[CABECERA_DOCUMENTO] ON;

INSERT INTO [dbo].[CABECERA_DOCUMENTO] (
    IDTRANSACCION, CODIGO_DOCUMENTO, NUMERO_SERIE, NUMERO_DOCUMENTO,
    FECHA_DOCUMENTO, CODIGO_MONEDA, TIPO_AUXILIAR,
    IDENTIDAD, NOMBRE,
    IMPORTE_SUBTOTAL, IMPORTE_IGV, IMPORTE_TOTAL,
    PORC_IMPUESTO, IMPORTE_INAFECTO,
    CODIGO_ESTADO, TIPO_CAMBIO, IDEMPRESA, IDSUCURSAL,
    USUARIO_CREACION, FECHA_CREACION
) VALUES (
    262944, '068', 142, 48490,
    GETDATE(), '01', '01',
    '43712654', 'QUISPE MAMANI ROSA INES',
    211.86, 38.14, 250.00,
    18.00, 0.00,
    '12', 3.368, 1, 172,
    'TEST', GETDATE()
);

SET IDENTITY_INSERT [dbo].[CABECERA_DOCUMENTO] OFF;

SET IDENTITY_INSERT [dbo].[DETALLE_DOCUMENTO] ON;

INSERT INTO [dbo].[DETALLE_DOCUMENTO] (
    IDTRANSACCION, SECUENCIA, CODIGO_PRODUCTO, CANTIDAD,
    PRECIO_UNITARIO, IMPORTE_SUBTOTAL, IMPORTE_IMPUESTO, IMPORTE_TOTAL,
    PORC_IMPUESTO, CODIGO_UNIMED, FLAG_INAFECTO, IMPORTE_ICBPER
) VALUES
    (262944, 1, 'V26MCFL006HUEME', 1.00, 211.8644, 211.86, 38.14, 250.00, 18.00, 'UN', 'N', 0.00);

SET IDENTITY_INSERT [dbo].[DETALLE_DOCUMENTO] OFF;
GO

-- ================================================================
-- ESCENARIO 4: Forzar captura — SIN INSERT necesario
-- IDTRANSACCION 262930 y 262931 ya existen en Soluflex con
-- CODIGO_ESTADO='12' pero el motor los saltó. Usá el botón
-- "Forzar captura" en la vista con cualquiera de esos IDs.
-- ================================================================

-- Verificación final:
SELECT IDTRANSACCION, CODIGO_DOCUMENTO, NUMERO_SERIE, NUMERO_DOCUMENTO, CODIGO_ESTADO
FROM [dbo].[CABECERA_DOCUMENTO]
WHERE IDTRANSACCION IN (262930, 262931, 262942, 262943, 262944)
ORDER BY IDTRANSACCION;
GO
